### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Note: If you do decide to rename the `ensenso_eef` package, don't forget to update the xacros in this package.

**Comment by gavanderhoorn** [comment]
O, and I also did not touch the 0.5m offset in Z direction between `tool0` and the N10 `base_link`.

**Comment by VictorLamoine** [comment]
No problem that I should be able to fix :)
Now I need to digest the changes and improve what you said

**Comment by gavanderhoorn** [comment]
And note that your ensenso has a -90 degree rotation over Y (ie: Z is forward facing). That is fine, but would probably need a rotation in the `tool0-ensenso_n10_base_link` fixed joint (or do that in the to-be-created `mounting_plate` link (or something)).

**Pull request merged**
